name: Get Time Action
description: Retrieves the current time in London and New York
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Replace with the desired Python version

    - name: Install Dependencies
      run: pip install pytz

    - name: Get Time
      run: python time_script.py
